In [1]:
import pandas as pd

In [2]:
external_factors = pd.read_csv('external_factors.csv')
matches = pd.read_csv('matchesk.csv')
player = pd.read_csv('playersk.csv')
team = pd.read_csv('teamsk.csv')
venue = pd.read_csv('venuesk.csv')

In [3]:
external_factors.head()

,match_id,weather_condition,temperature,travel_distance_km,social_sentiment_home,social_sentiment_away,betting_odds_home,referee_strictness,fatigue_diff
0,M0001,Rain,20.6,6290,0.83,-0.14,2.79,8.0,1.2
1,M0002,Sunny,21.0,1356,0.75,-0.28,1.76,7.1,-1.5
2,M0003,Hot,29.7,3476,-0.15,0.10,3.26,6.8,-4.3
3,M0004,Hot,27.7,5745,-0.17,0.38,3.35,6.9,21.8
4,M0005,Sunny,20.4,5362,0.21,0.15,1.72,7.1,17.4

In [4]:
matches.head()

,match_id,date,team_home,team_away,venue_id,group_stage,predicted_win_prob_home,goals_home,goals_away,xG_home,xG_away,attendance
0,M0001,2026-06-11,T039,T028,V08,Knockout,0.531,0,4,1.28,1.07,66996
1,M0002,2026-06-12,T029,T047,V08,Group B,0.489,3,0,1.82,2.20,62122
2,M0003,2026-06-13,T015,T007,V03,Group B,0.398,3,3,1.02,1.76,69850
3,M0004,2026-06-14,T043,T044,V01,Group A,0.449,0,0,0.91,1.58,62350
4,M0005,2026-06-15,T008,T008,V08,Group B,0.447,1,4,1.84,1.79,62472

In [5]:
player.head()

,player_id,player_name,team_id,position,age,matches_played_2025_26,goals_2025_26,assists_2025_26,xG,xA,minutes_played,injury_risk,market_value_million,nationality,club,fatigue_score,social_mention_count
0,P0001,Lionel Messi,T017,DF,36,16,18,3,0.65,0.33,459,Low,100,France,Bayern Munich,79.4,174823
1,P0002,Erling Haaland,T009,DF,25,12,14,12,0.58,0.46,3385,Low,52,Argentina,Real Madrid,87.1,218135
2,P0003,Neymar Jr,T033,GK,34,38,3,11,0.90,0.22,3549,Medium,74,Brazil,Manchester City,59.6,111511
3,P0004,Erling Haaland,T020,FW,22,33,20,12,0.94,0.57,2759,Low,104,Germany,Bayern Munich,81.7,225461
4,P0005,Thomas Muller,T013,DF,33,12,12,13,0.27,0.29,1311,Low,63,France,Manchester City,56.2,150830

In [6]:
team.head()

,team_id,team_name,fifa_rank,elo_rating,confederation,squad_size,avg_age,market_value_million,recent_form,goals_scored_last_12m,goals_conceded_last_12m,head_coach
0,T001,Brazil,52,1566,UEFA,24,25.4,246,WDWLW,68,38,Scaloni
1,T002,Argentina,93,1673,CONMEBOL,24,27.2,963,LWDWW,65,27,Scaloni
2,T003,France,15,1787,AFC,25,24.0,588,LWDWW,72,21,Flick
3,T004,England,72,2000,AFC,24,25.8,1028,WWDLW,50,50,Scaloni
4,T005,Germany,61,1715,AFC,22,25.5,650,LWDWW,54,59,Flick

In [7]:
venue.head()

,venue_id,venue_name,city,country,capacity,avg_temperature,humidity,pitch_quality_score
0,V01,MetLife,New York,USA,82500,24.5,55,9.2
1,V02,SoFi,LA,USA,70000,26.0,48,9.5
2,V03,AT&T,Dallas,USA,80000,28.5,62,8.8
3,V04,Azteca,Mexico City,Mexico,87000,27.0,58,9.0
4,V05,BC Place,Vancouver,Canada,54000,19.0,65,8.5

In [ ]:
# venue - venue id, venue_name,city, country, avg_temp, humidity, pitch_quality
# external_factors - travel_distance_km, match_id
# matches - match_id, date, team_home, team_away, venue_id
# player - team_id, matches_played_2025_26,	goals_2025_26
# team - team_id, team_name, goals_scored_last_12m,	goals_conceded_last_12m

# try to merge tables

In [10]:
print('venue keys: ', venue.keys())
print('external keys: ', external_factors.keys())
print('match keys: ', matches.keys())
print('player keys: ', player.keys())
print('team keys: ', team.keys())

venue keys:  Index(['venue_id', 'venue_name', 'city', 'country', 'capacity',
       'avg_temperature', 'humidity', 'pitch_quality_score'],
      dtype='str')
external keys:  Index(['match_id', 'weather_condition', 'temperature', 'travel_distance_km',
       'social_sentiment_home', 'social_sentiment_away', 'betting_odds_home',
       'referee_strictness', 'fatigue_diff'],
      dtype='str')
match keys:  Index(['match_id', 'date', 'team_home', 'team_away', 'venue_id', 'group_stage',
       'predicted_win_prob_home', 'goals_home', 'goals_away', 'xG_home',
       'xG_away', 'attendance'],
      dtype='str')
player keys:  Index(['player_id', 'player_name', 'team_id', 'position', 'age',
       'matches_played_2025_26', 'goals_2025_26', 'assists_2025_26', 'xG',
       'xA', 'minutes_played', 'injury_risk', 'market_value_million',
       'nationality', 'club', 'fatigue_score', 'social_mention_count'],
      dtype='str')
team keys:  Index(['team_id', 'team_name', 'fifa_rank', 'elo_rating', 'confederation',
       'squad_size', 'avg_age', 'market_value_million', 'recent_form',
       'goals_scored_last_12m', 'goals_conceded_last_12m', 'head_coach'],
      dtype='str')

In [15]:
venue2 = venue[['venue_id', 'venue_name', 'city', 'country', 'avg_temperature', 'humidity', 'pitch_quality_score']]

In [24]:
ext_fact = external_factors[['match_id', 'travel_distance_km', 'weather_condition', 'temperature']]

In [18]:
matches2 = matches[['match_id', 'date', 'team_home', 'team_away', 'venue_id', 'group_stage', 'predicted_win_prob_home', 'goals_home', 'goals_away']]

In [21]:
players = player[['player_id', 'player_name', 'team_id', 'position', 'age', 'matches_played_2025_26', 'goals_2025_26', 'assists_2025_26', 'minutes_played', 'injury_risk', 'fatigue_score']]

In [22]:
teams = team[['team_id', 'team_name', 'recent_form', 'goals_scored_last_12m', 'goals_conceded_last_12m']]

In [26]:
matchmerg = pd.merge(matches2, venue2, on=['venue_id'])

In [27]:
matchmerge = pd.merge(matchmerg, ext_fact, on=['match_id'])

In [28]:
teamplay = pd.merge(teams, players, on=['team_id'])

In [31]:
teamplay.head()

,team_id,team_name,recent_form,goals_scored_last_12m,goals_conceded_last_12m,player_id,player_name,position,age,matches_played_2025_26,goals_2025_26,assists_2025_26,minutes_played,injury_risk,fatigue_score
0,T001,Brazil,WDWLW,68,38,P0023,Harry Kane,MF,36,30,16,15,1398,Low,61.5
1,T001,Brazil,WDWLW,68,38,P0038,Thomas Muller,DF,30,41,23,2,1117,Low,82.9
2,T001,Brazil,WDWLW,68,38,P0060,Jude Bellingham,DF,30,43,9,16,1406,Low,53.2
3,T001,Brazil,WDWLW,68,38,P0064,Lionel Messi,MF,24,18,7,15,2295,Low,68.8
4,T001,Brazil,WDWLW,68,38,P0076,Thomas Muller,MF,18,29,24,8,2522,Low,42.8

In [32]:
matchmerge.head()

,match_id,date,team_home,team_away,venue_id,group_stage,predicted_win_prob_home,goals_home,goals_away,venue_name,city,country,avg_temperature,humidity,pitch_quality_score,travel_distance_km,weather_condition,temperature
0,M0001,2026-06-11,T039,T028,V08,Knockout,0.531,0,4,NRG,Houston,USA,29.0,70,8.7,6290,Rain,20.6
1,M0002,2026-06-12,T029,T047,V08,Group B,0.489,3,0,NRG,Houston,USA,29.0,70,8.7,1356,Sunny,21.0
2,M0003,2026-06-13,T015,T007,V03,Group B,0.398,3,3,AT&T,Dallas,USA,28.5,62,8.8,3476,Hot,29.7
3,M0004,2026-06-14,T043,T044,V01,Group A,0.449,0,0,MetLife,New York,USA,24.5,55,9.2,5745,Hot,27.7
4,M0005,2026-06-15,T008,T008,V08,Group B,0.447,1,4,NRG,Houston,USA,29.0,70,8.7,5362,Sunny,20.4